### ISSUE TITLE
Need change of functionality

### ISSUE THREAD

**Issue by shifatul-i** [EntireNewsProject/Python-Backend#3]
We don't need to save json data, use '**send_post_req**' function to send post request to server inside the **'for loop**' of '**scrap_data**' function

https://github.com/EntireNewsProject/Python-Backend/blob/b457f5d4ed356537bb240d5dd0e82ca20865e88d/scrapNrequest.py#L62

**Comment by lengx03** [comment]
ok

**Comment by shifatul-i** [comment]
Mark it done, once you are done

**Comment by khushaljobanputra** [comment]
Hey leng,
If you done with this enhancement then please go ahead and close this issue
