### ISSUE TITLE
different approach

### ISSUE THREAD

**Issue by lengx03** [EntireNewsProject/Python-Backend#5]
This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.

will this work {'token': 'TOKEN'}

**Comment by shifatul-i** [comment]
Need clarification

**Comment by khushaljobanputra** [comment]
Hey leng,
Go ahead and close this issue if it has been solved.
