### ISSUE TITLE
failed post

### ISSUE THREAD

**Issue by lengx03** [EntireNewsProject/Python-Backend#6]
scraping data started
scraping data end
send post req
failed to post data, code: 401 message: All information not provided

**Comment by lengx03** [comment]
the token is xxx right? if so i need help stuck and have no clue about what to do

**Comment by kishanbshah** [comment]
Hey Leng, text Sif on slack about this. Thanks!
@Kishanshah147 ok thanks

**Comment by shifatul-i** [comment]
@leng03 Push ur CODE first
@ThunderRoid yes i did...if i'm missing somethings lmk cus i think it might be. I don't need login function yet, just token auth for now right?

**Comment by khushaljobanputra** [comment]
The error that your post request is giving means that all the requires data is not being posted. Could you post the data you are trying to post on the weblink on slack so that I can tally it to the required fields of the database.

**Comment by khushaljobanputra** [comment]
Issue fixed
-Leng and Khushal
